# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/uom_pay.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/uom_pay.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x16protobuf/uom_pay.proto\"q\n\nUOMPayload\x12\"\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x12.UOMPayload.Action\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"1\n\x06\x41\x63tion\x12\x10\n\x0c\x41\x43TION_UNSET\x10\x00\x12\x0b\n\x07PROPOSE\x10\x01\x12\x08\n\x04VOTE\x10\x02\"<\n\x0bUOMProposal\x12\x0f\n\x07setting\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\r\n\x05nonce\x18\x03 \x01(\t\"k\n\x07UOMVote\x12\x13\n\x0bproposal_id\x18\x01 \x01(\t\x12\x1b\n\x04vote\x18\x02 \x01(\x0e\x32\r.UOMVote.Vote\".\n\x04Vote\x12\x0e\n\nVOTE_UNSET\x10\x00\x12\n\n\x06\x41\x43\x43\x45PT\x10\x01\x12\n\n\x06REJECT\x10\x02\"\xab\x01\n\x0cUOMCandidate\x12\x13\n\x0bproposal_id\x18\x01 \x01(\t\x12\x1e\n\x08proposal\x18\x02 \x01(\x0b\x32\x0c.UOMProposal\x12\'\n\x05votes\x18\x03 \x03(\x0b\x32\x18.UOMCandidate.VoteRecord\x1a=\n\nVoteRecord\x12\x12\n\npublic_key\x18\x01 \x01(\t\x12\x1b\n\x04vote\x18\x02 \x01(\x0e\x32\r.UOMVote.Vote\"2\n\rUOMCandidates\x12!\n\ncandidates\x18\x01 \x03(\x0b\x32\r.UOMCandidateB\x19\n\x15sawtooth.uom.protobufP\x01\x62\x06proto3')
)



_UOMPAYLOAD_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='UOMPayload.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACTION_UNSET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROPOSE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VOTE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=90,
  serialized_end=139,
)
_sym_db.RegisterEnumDescriptor(_UOMPAYLOAD_ACTION)

_UOMVOTE_VOTE = _descriptor.EnumDescriptor(
  name='Vote',
  full_name='UOMVote.Vote',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VOTE_UNSET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACCEPT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REJECT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=264,
  serialized_end=310,
)
_sym_db.RegisterEnumDescriptor(_UOMVOTE_VOTE)


_UOMPAYLOAD = _descriptor.Descriptor(
  name='UOMPayload',
  full_name='UOMPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='UOMPayload.action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='UOMPayload.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _UOMPAYLOAD_ACTION,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=139,
)


_UOMPROPOSAL = _descriptor.Descriptor(
  name='UOMProposal',
  full_name='UOMProposal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='setting', full_name='UOMProposal.setting', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='UOMProposal.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='UOMProposal.nonce', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=201,
)


_UOMVOTE = _descriptor.Descriptor(
  name='UOMVote',
  full_name='UOMVote',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proposal_id', full_name='UOMVote.proposal_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vote', full_name='UOMVote.vote', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _UOMVOTE_VOTE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=310,
)


_UOMCANDIDATE_VOTERECORD = _descriptor.Descriptor(
  name='VoteRecord',
  full_name='UOMCandidate.VoteRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='public_key', full_name='UOMCandidate.VoteRecord.public_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vote', full_name='UOMCandidate.VoteRecord.vote', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=484,
)

_UOMCANDIDATE = _descriptor.Descriptor(
  name='UOMCandidate',
  full_name='UOMCandidate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proposal_id', full_name='UOMCandidate.proposal_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proposal', full_name='UOMCandidate.proposal', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='votes', full_name='UOMCandidate.votes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_UOMCANDIDATE_VOTERECORD, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=484,
)


_UOMCANDIDATES = _descriptor.Descriptor(
  name='UOMCandidates',
  full_name='UOMCandidates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='candidates', full_name='UOMCandidates.candidates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=486,
  serialized_end=536,
)

_UOMPAYLOAD.fields_by_name['action'].enum_type = _UOMPAYLOAD_ACTION
_UOMPAYLOAD_ACTION.containing_type = _UOMPAYLOAD
_UOMVOTE.fields_by_name['vote'].enum_type = _UOMVOTE_VOTE
_UOMVOTE_VOTE.containing_type = _UOMVOTE
_UOMCANDIDATE_VOTERECORD.fields_by_name['vote'].enum_type = _UOMVOTE_VOTE
_UOMCANDIDATE_VOTERECORD.containing_type = _UOMCANDIDATE
_UOMCANDIDATE.fields_by_name['proposal'].message_type = _UOMPROPOSAL
_UOMCANDIDATE.fields_by_name['votes'].message_type = _UOMCANDIDATE_VOTERECORD
_UOMCANDIDATES.fields_by_name['candidates'].message_type = _UOMCANDIDATE
DESCRIPTOR.message_types_by_name['UOMPayload'] = _UOMPAYLOAD
DESCRIPTOR.message_types_by_name['UOMProposal'] = _UOMPROPOSAL
DESCRIPTOR.message_types_by_name['UOMVote'] = _UOMVOTE
DESCRIPTOR.message_types_by_name['UOMCandidate'] = _UOMCANDIDATE
DESCRIPTOR.message_types_by_name['UOMCandidates'] = _UOMCANDIDATES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UOMPayload = _reflection.GeneratedProtocolMessageType('UOMPayload', (_message.Message,), dict(
  DESCRIPTOR = _UOMPAYLOAD,
  __module__ = 'protobuf.uom_pay_pb2'
  # @@protoc_insertion_point(class_scope:UOMPayload)
  ))
_sym_db.RegisterMessage(UOMPayload)

UOMProposal = _reflection.GeneratedProtocolMessageType('UOMProposal', (_message.Message,), dict(
  DESCRIPTOR = _UOMPROPOSAL,
  __module__ = 'protobuf.uom_pay_pb2'
  # @@protoc_insertion_point(class_scope:UOMProposal)
  ))
_sym_db.RegisterMessage(UOMProposal)

UOMVote = _reflection.GeneratedProtocolMessageType('UOMVote', (_message.Message,), dict(
  DESCRIPTOR = _UOMVOTE,
  __module__ = 'protobuf.uom_pay_pb2'
  # @@protoc_insertion_point(class_scope:UOMVote)
  ))
_sym_db.RegisterMessage(UOMVote)

UOMCandidate = _reflection.GeneratedProtocolMessageType('UOMCandidate', (_message.Message,), dict(

  VoteRecord = _reflection.GeneratedProtocolMessageType('VoteRecord', (_message.Message,), dict(
    DESCRIPTOR = _UOMCANDIDATE_VOTERECORD,
    __module__ = 'protobuf.uom_pay_pb2'
    # @@protoc_insertion_point(class_scope:UOMCandidate.VoteRecord)
    ))
  ,
  DESCRIPTOR = _UOMCANDIDATE,
  __module__ = 'protobuf.uom_pay_pb2'
  # @@protoc_insertion_point(class_scope:UOMCandidate)
  ))
_sym_db.RegisterMessage(UOMCandidate)
_sym_db.RegisterMessage(UOMCandidate.VoteRecord)

UOMCandidates = _reflection.GeneratedProtocolMessageType('UOMCandidates', (_message.Message,), dict(
  DESCRIPTOR = _UOMCANDIDATES,
  __module__ = 'protobuf.uom_pay_pb2'
  # @@protoc_insertion_point(class_scope:UOMCandidates)
  ))
_sym_db.RegisterMessage(UOMCandidates)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\025sawtooth.uom.protobufP\001'))
# @@protoc_insertion_point(module_scope)
